#!/bin/bash
# Quick URL Access Guide - Copy & Paste into Browser

echo "==================================="
echo "  KRAYIN CRM DEVOPS - URL GUIDE"
echo "==================================="
echo ""
echo "📊 DOCKER CONTAINERS (Host Machine)"
echo "-----------------------------------"
echo "✓ SonarQube:      http://localhost:9000"
echo "✓ Artifactory:    http://localhost:8083"
echo "✓ Jenkins:        http://localhost:8082"
echo ""
echo "🚀 KUBERNETES SERVICES (K8s Cluster)"
echo "-----------------------------------"
echo "✓ Krayin CRM:     http://localhost:30080"
echo "✓ Prometheus:     http://localhost:30090"
echo "✓ Grafana:        http://localhost:30300"
echo "✓ Loki:           http://localhost:30100"
echo ""
echo "🔐 CREDENTIALS"
echo "-----------------------------------"
echo "Krayin CRM Admin:"
echo "  Email:    admin@example.com"
echo "  Password: admin123"
echo ""
echo "Jenkins Initial Setup:"
echo "  Password: 857a566964964703a4cdf9597467c01d"
echo ""
echo "SonarQube:"
echo "  User:     admin"
echo "  Password: admin"
echo ""
echo "Grafana:"
echo "  User:     admin"
echo "  Password: admin"
echo ""
echo "JFrog Artifactory:"
echo "  User:     mukeshjpr432"
echo "  Password: DoHare@1991"
echo ""
echo "==================================="
echo "Status: All Services Running ✓"
echo "==================================="
