pipeline {
    agent any

    environment {
        SONAR_HOST_URL = 'http://host.docker.internal:9000'
        IMAGE_NAME = 'trial8mlq0s.jfrog.io/docker-local/krayin-crm'
        IMAGE_TAG = 'latest'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/YOUR_USERNAME/YOUR_REPOSITORY.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    bat '''
                    sonar-scanner ^
                    -Dsonar.projectKey=laravel-crm ^
                    -Dsonar.sources=. ^
                    -Dsonar.host.url=%SONAR_HOST_URL% ^
                    -Dsonar.login=admin ^
                    -Dsonar.password=admin
                    '''
                }
            }
        }

        stage('Composer Install') {
            steps {
                bat 'composer install'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %IMAGE_NAME%:%IMAGE_TAG% .'
            }
        }

        stage('Trivy Security Scan') {
            steps {
                bat 'trivy image %IMAGE_NAME%:%IMAGE_TAG%'
            }
        }

        stage('Push Image to JFrog') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'jfrog-creds',
                    usernameVariable: 'JFROG_USER',
                    passwordVariable: 'JFROG_PASS'
                )]) {

                    bat '''
                    docker login trial8mlq0s.jfrog.io -u %JFROG_USER% -p %JFROG_PASS%
                    docker push %IMAGE_NAME%:%IMAGE_TAG%
                    '''
                }
            }
        }

        stage('Load Image into KIND') {
            steps {
                bat 'kind load docker-image %IMAGE_NAME%:%IMAGE_TAG% --name laravel-devops'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                bat 'kubectl apply -f k8s/'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}