apiVersion: v1
kind: Secret

metadata:
  name: crm-secret

type: Opaque

stringData:
  APP_KEY: "base64:Q22dL8mw4QhqAa7hrnoyXk3oED5IEgZpJihXpWqkh3E="
  DB_HOST: "host.docker.internal"
  DB_DATABASE: "laravel-crm"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"